services:
  # telemetry:
  #   build:
  #     context: ..
  #     dockerfile: docker/Dockerfile
  #   ports:
  #     - "${TELEMETRY_PORT:-8080}:${TELEMETRY_PORT:-8080}"
  #   environment:
  #     - TELEMETRY_PORT=${TELEMETRY_PORT:-8080}
  #     - TELEMETRY_METRICS_PATH=${TELEMETRY_METRICS_PATH:-/metrics}

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./supervision/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=10m'
    ports:
      - "9090:9090"
    # depends_on:
    #   - telemetry

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    env_file:
      - ../.env.secret
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    volumes:
      - grafana-data:/var/lib/grafana
      - ./supervision/grafana/dashboards:/etc/grafana/dashboards
      - ./supervision/grafana/alerting:/etc/grafana/provisioning/alerting
      - ./supervision/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./supervision/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources

volumes:
  grafana-data:
