services:
  telemetry:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - "${TELEMETRY_PORT:-8080}:${TELEMETRY_PORT:-8080}"
    environment:
      - TELEMETRY_PORT=${TELEMETRY_PORT:-8080}
      - TELEMETRY_METRICS_PATH=${TELEMETRY_METRICS_PATH:-/metrics}