global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'system_metrics'
    metrics_path: "/metrics/system"
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'status_metrics'
    metrics_path: "/metrics/statut"
    static_configs:
      - targets: ['host.docker.internal:8080']